### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by jgesell** [utsw-bicf/auto-docker#2]
Create a new ReadMe file to explain how to setup and use this program.

**Comment by GHAStVHenry** [comment]
> Fork this repository from the master branch, and rename it to suite your needs
should be "use this template" instead?
![image](https://user-images.githubusercontent.com/38675268/98836964-fba1fb80-2407-11eb-8d49-762d2483e18c.png)

**Comment by GHAStVHenry** [comment]
> Setup the following secrets:

should specify repository secrets, not organization?

**Comment by vsmalladi** [comment]
Yes should be a repository secretes

**Comment by GHAStVHenry** [comment]
Yeah, I know... these are edits for the readme...

**Comment by GHAStVHenry** [comment]
> Change the name of the base image to suite your needs. So, since we are the bicf, we call ours bicfbase. You will need to do this in the main directory, as well as in the relations.yaml file.

need to specify why branch to edit on

**Comment by vsmalladi** [comment]
> > Fork this repository from the master branch, and rename it to suite your needs
> 
> should be "use this template" instead?
> ![image](https://user-images.githubusercontent.com/38675268/98836964-fba1fb80-2407-11eb-8d49-762d2483e18c.png)

Yes try that. We haven't tried that and didn't know the behavior

**Comment by GHAStVHenry** [comment]
Initial fork/template, the "Initial commit" will fail github CI because the secrets aren't there yet... that's fine... but if you want to clean it up... if you could detect that it is the "Initial commit" and not run CI that would be nice

**Comment by GHAStVHenry** [comment]
> Fork this repository from the master branch, and rename it to suite your needs

should be "use this template" instead (I think "use this template" is GitHub's new lable for the fork button... but you should refer to that in the readme, because that is what users will see)? Also "Include all branches" should NOT be checked

---
> Setup the following secrets:

should specify repository secrets, not organization?

---
> Change the name of the base image to suite your needs. So, since we are the bicf, we call ours bicfbase. You will need to do this in the main directory, as well as in the relations.yaml file.

order is
commit and push replacement base to main (leaving old base and relations.yaml unchanged)
AFTER workflow CI is complete for that commit+push to main (make sure you pull latest) then remove old base folder and remove old base reference from relations.yaml (old base may already be removed from relations.yaml?) (ignore CI fail for this commit)
merge main into develop (ignore CI fail for this merge)

---
Need to add feel free to replace the README.md... and what branch they are allowed to update that... develop I assume... with that commit cause an error?

---
> This suite is setup assuming that all of your images have the base image as their ultimate parent. This image is built off the publically available Ubuntu 18.04 image, with some common tools such as git, parallel, pbzip2 and others installed. It is meant to be fairly light-weight.

you aren't the boss of me... I set the new base for GUDMAP as Ubuntu 20.10... shouldn't assume that people will want to use your base, you told them to feel free to replace your base if they want, so this paragraph should be generalized... it would be OK to use your base as an example

---
> Using the relations.yaml file, it is very easy to keep track of what images are built on top of other images.

I'd be careful talking about relations.yaml too much straight off the bat... the only time people will need to even open relations.yaml is if they are terminating an image right? so I would not mention it until you talk about that

---
> There should be three branches of this repository at any given time, we will call them main, develop, and issue.

this is misleading... at any given time, I probably only have main and develop... I only have issue branches when I'm creating/modifying images and I could have multiple issue branches open at one time... I would just say main and develop, with issue branches open when creating new images or updating images

---
> This branch is the most maliable, and it is also the only branch where there should exist more than one; specifically one per image created/in development. Each issue can have only ONE modified Dockerfile, so if you need to modify more than one Dockerfile, you must create two entries in this branch.

this is confusing... I mean I get what it means, but that's because I know how it works... I'm not sure an outside user will

---
> The thought process for this branch is that these images are still in testing by the creator, and so are not meant for anyone else's use.

the "issue branch" is continually referred to as one branch... if I were an outside user, I would think that I have to create a branch named "Issue" and I can only have one of them... consider refactoring

---
> Within the issue branch, a new relations.yaml file is created, which takes the current relations.yaml from the develop branch, and updates it with the new Dockerfile information. Once it is pushed to develop.

I would point out that the CI is going to create a new commit to your branch (as long as there is no error), so if the user goes to modify their local repo clone, they need to make sure they pull from the origin

---
> There is a section in the relations.yaml called "terminated". This section is special, and should only be updated on the develop branch. This section is reserved for images that are no longer to be updated whenever a parent image is updated (for example, if there are licensing issues, or logins that make an automated build impossible).

I think this is a very important step in the life cycle and should be put under it's own heading

---

## This is a large and detailed readme... I would consider moving this to a wiki instead so you can use links for easier navigation... also that would free up the forker to be able to replace your readme to their own, without loosing the instructions

**Comment by vsmalladi** [comment]
@jgesell I agree lets have some in Readme and then create a wiki

**Comment by vsmalladi** [comment]
@jgesell Well all my changes are in the readme. So once wiki is updated with @GHAStVHenry then i think we can close this issue.
